apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  promotionTemplate:
    spec:
      steps:
        - as: git-clone
          config:
            checkout:
              - branch: main
                path: ./src
            repoURL: ${{ vars.gitRepo }}
          uses: git-clone
        - as: update-image
          uses: yaml-update
          config:
            path: ./src/resources/pod.yaml
            updates:
              - key: spec.containers.0.image
                value: ghcr.io/hairyhum/steps-test:${{ imageFrom("ghcr.io/hairyhum/steps-test").Tag }}
        - as: custom
          uses: kyverno-apply-prod
          config:
            # image_user: ${{ secret('kargo-demo-repo').username }}
            # image_repo: ghcr.io
            # image_pass: ${{ secret('kargo-demo-repo').password }} 
            policies_dir: ./src/policies/prod
            resources_dir: ./src/resources
      vars:
        - name: gitRepo
          value: https://github.com/hairyhum/steps-test.git
  requestedFreight:
    - origin:
        kind: Warehouse
        name: images
      sources:
        direct: true
        stages: []
