apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  promotionTemplate:
    spec:
      steps:
        - as: git-clone
          config:
            checkout:
              - branch: main
                path: ./src
            repoURL: ${{ vars.gitRepo }}
          uses: git-clone
        - as: custom
          uses: kyverno-apply-prod
          config:
            image_user: hairyhum
            image_repo: ghcr.io
            image_pass: ${{ secret('ghcr-pat') }} 
            policies_dir: ./src/policies/prod
            resources_dir: ./src/resources
      vars:
        - name: gitRepo
          value: https://github.com/hairyhum/steps-test.git
  requestedFreight:
    - origin:
        kind: Warehouse
        name: test
      sources:
        direct: true
        stages: []
